[2023-03-23T15:56:30.900+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asndjfsdf_v02.extract scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2023-03-23T15:56:30.912+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asndjfsdf_v02.extract scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2023-03-23T15:56:30.912+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-23T15:56:30.913+0000] {taskinstance.py:1283} INFO - Starting attempt 5 of 6
[2023-03-23T15:56:30.914+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-23T15:56:30.932+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract> on 2023-03-22 00:00:00+00:00
[2023-03-23T15:56:30.936+0000] {standard_task_runner.py:55} INFO - Started process 2135 to run task
[2023-03-23T15:56:30.939+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'asndjfsdf_v02', 'extract', 'scheduled__2023-03-22T00:00:00+00:00', '--job-id', '452', '--raw', '--subdir', 'DAGS_FOLDER/ashfjasdg.py', '--cfg-path', '/tmp/tmp93z5cqp3']
[2023-03-23T15:56:30.942+0000] {standard_task_runner.py:83} INFO - Job 452: Subtask extract
[2023-03-23T15:56:31.011+0000] {task_command.py:388} INFO - Running <TaskInstance: asndjfsdf_v02.extract scheduled__2023-03-22T00:00:00+00:00 [running]> on host 7a7b82ed390a
[2023-03-23T15:56:31.091+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mr.Phi
AIRFLOW_CTX_DAG_ID=asndjfsdf_v02
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-22T00:00:00+00:00
[2023-03-23T15:56:31.540+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:56:31,540 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
[2023-03-23T15:56:31.540+0000] {log.py:128} INFO - SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
[2023-03-23T15:56:31.541+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:56:31,541 INFO sqlalchemy.engine.Engine [raw sql] ()
[2023-03-23T15:56:31.541+0000] {log.py:128} INFO - [raw sql] ()
[2023-03-23T15:56:31.544+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:56:31,544 INFO sqlalchemy.engine.Engine SELECT schema_name()
[2023-03-23T15:56:31.544+0000] {log.py:128} INFO - SELECT schema_name()
[2023-03-23T15:56:31.545+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:56:31,545 INFO sqlalchemy.engine.Engine [generated in 0.00080s] ()
[2023-03-23T15:56:31.545+0000] {log.py:128} INFO - [generated in 0.00080s] ()
[2023-03-23T15:56:31.559+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:56:31,559 INFO sqlalchemy.engine.Engine SELECT CAST('test max support' AS NVARCHAR(max))
[2023-03-23T15:56:31.559+0000] {log.py:128} INFO - SELECT CAST('test max support' AS NVARCHAR(max))
[2023-03-23T15:56:31.560+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:56:31,560 INFO sqlalchemy.engine.Engine [generated in 0.00113s] ()
[2023-03-23T15:56:31.560+0000] {log.py:128} INFO - [generated in 0.00113s] ()
[2023-03-23T15:56:31.568+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:56:31,568 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
[2023-03-23T15:56:31.568+0000] {log.py:128} INFO - SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
[2023-03-23T15:56:31.568+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:56:31,568 INFO sqlalchemy.engine.Engine [generated in 0.00100s] ('dbo', 'BASE TABLE')
[2023-03-23T15:56:31.568+0000] {log.py:128} INFO - [generated in 0.00100s] ('dbo', 'BASE TABLE')
[2023-03-23T15:56:31.587+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:56:31,587 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
[2023-03-23T15:56:31.587+0000] {log.py:128} INFO - SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
[2023-03-23T15:56:31.588+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:56:31,588 INFO sqlalchemy.engine.Engine [cached since 0.02099s ago] ('dbo', 'VIEW')
[2023-03-23T15:56:31.588+0000] {log.py:128} INFO - [cached since 0.02099s ago] ('dbo', 'VIEW')
[2023-03-23T15:56:31.606+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 320, in read_sql_table
    meta.reflect(only=[table_name], views=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4891, in reflect
    "in %r%s: (%s)" % (bind.engine, s, ", ".join(missing))
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mssql+pyodbc://sa:***@host.docker.internal:1433/DE_Data_Lake?driver=ODBC+Driver+17+for+SQL+Server): (jobs_v04)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ashfjasdg.py", line 32, in extract
    df = pd.read_sql_table('jobs_v04', engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 322, in read_sql_table
    raise ValueError(f"Table {table_name} not found") from err
ValueError: Table jobs_v04 not found
[2023-03-23T15:56:31.619+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=asndjfsdf_v02, task_id=extract, execution_date=20230322T000000, start_date=20230323T155630, end_date=20230323T155631
[2023-03-23T15:56:31.632+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 452 for task extract (Table jobs_v04 not found; 2135)
[2023-03-23T15:56:31.675+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-23T15:56:31.706+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
