[2023-03-23T15:36:22.755+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asndjfsdf_v02.extract scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2023-03-23T15:36:22.779+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asndjfsdf_v02.extract scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2023-03-23T15:36:22.780+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-23T15:36:22.780+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-23T15:36:22.781+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-23T15:36:22.813+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract> on 2023-03-22 00:00:00+00:00
[2023-03-23T15:36:22.819+0000] {standard_task_runner.py:55} INFO - Started process 240 to run task
[2023-03-23T15:36:22.825+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'asndjfsdf_v02', 'extract', 'scheduled__2023-03-22T00:00:00+00:00', '--job-id', '443', '--raw', '--subdir', 'DAGS_FOLDER/ashfjasdg.py', '--cfg-path', '/tmp/tmpvegglkdp']
[2023-03-23T15:36:22.830+0000] {standard_task_runner.py:83} INFO - Job 443: Subtask extract
[2023-03-23T15:36:22.951+0000] {task_command.py:388} INFO - Running <TaskInstance: asndjfsdf_v02.extract scheduled__2023-03-22T00:00:00+00:00 [running]> on host 7a7b82ed390a
[2023-03-23T15:36:23.067+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mr.Phi
AIRFLOW_CTX_DAG_ID=asndjfsdf_v02
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-22T00:00:00+00:00
[2023-03-23T15:36:23.604+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:36:23,604 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
[2023-03-23T15:36:23.604+0000] {log.py:128} INFO - SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
[2023-03-23T15:36:23.605+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:36:23,605 INFO sqlalchemy.engine.Engine [raw sql] ()
[2023-03-23T15:36:23.605+0000] {log.py:128} INFO - [raw sql] ()
[2023-03-23T15:36:23.609+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:36:23,609 INFO sqlalchemy.engine.Engine SELECT schema_name()
[2023-03-23T15:36:23.609+0000] {log.py:128} INFO - SELECT schema_name()
[2023-03-23T15:36:23.610+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:36:23,610 INFO sqlalchemy.engine.Engine [generated in 0.00104s] ()
[2023-03-23T15:36:23.610+0000] {log.py:128} INFO - [generated in 0.00104s] ()
[2023-03-23T15:36:23.617+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:36:23,617 INFO sqlalchemy.engine.Engine SELECT CAST('test max support' AS NVARCHAR(max))
[2023-03-23T15:36:23.617+0000] {log.py:128} INFO - SELECT CAST('test max support' AS NVARCHAR(max))
[2023-03-23T15:36:23.618+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:36:23,618 INFO sqlalchemy.engine.Engine [generated in 0.00124s] ()
[2023-03-23T15:36:23.618+0000] {log.py:128} INFO - [generated in 0.00124s] ()
[2023-03-23T15:36:23.626+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:36:23,626 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
[2023-03-23T15:36:23.626+0000] {log.py:128} INFO - SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
[2023-03-23T15:36:23.627+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:36:23,627 INFO sqlalchemy.engine.Engine [generated in 0.00113s] ('dbo', 'BASE TABLE')
[2023-03-23T15:36:23.627+0000] {log.py:128} INFO - [generated in 0.00113s] ('dbo', 'BASE TABLE')
[2023-03-23T15:36:23.646+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:36:23,646 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
[2023-03-23T15:36:23.646+0000] {log.py:128} INFO - SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) ORDER BY [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME]
[2023-03-23T15:36:23.649+0000] {logging_mixin.py:137} INFO - 2023-03-23 15:36:23,649 INFO sqlalchemy.engine.Engine [cached since 0.02277s ago] ('dbo', 'VIEW')
[2023-03-23T15:36:23.649+0000] {log.py:128} INFO - [cached since 0.02277s ago] ('dbo', 'VIEW')
[2023-03-23T15:36:23.669+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 320, in read_sql_table
    meta.reflect(only=[table_name], views=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4891, in reflect
    "in %r%s: (%s)" % (bind.engine, s, ", ".join(missing))
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(mssql+pyodbc://sa:***@host.docker.internal:1433/DE_Data_Lake?driver=ODBC+Driver+17+for+SQL+Server): (jobs_v04)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ashfjasdg.py", line 32, in extract
    df = pd.read_sql_table('jobs_v04', engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 322, in read_sql_table
    raise ValueError(f"Table {table_name} not found") from err
ValueError: Table jobs_v04 not found
[2023-03-23T15:36:23.698+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=asndjfsdf_v02, task_id=extract, execution_date=20230322T000000, start_date=20230323T153622, end_date=20230323T153623
[2023-03-23T15:36:23.717+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 443 for task extract (Table jobs_v04 not found; 240)
[2023-03-23T15:36:23.760+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-23T15:36:23.784+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
