[2023-03-21T11:25:13.830+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_operator_v04.install_odbc_3 scheduled__2023-03-20T00:00:00+00:00 [queued]>
[2023-03-21T11:25:13.851+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_operator_v04.install_odbc_3 scheduled__2023-03-20T00:00:00+00:00 [queued]>
[2023-03-21T11:25:13.852+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T11:25:13.853+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-21T11:25:13.854+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T11:25:13.891+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): install_odbc_3> on 2023-03-20 00:00:00+00:00
[2023-03-21T11:25:13.904+0000] {standard_task_runner.py:55} INFO - Started process 7333 to run task
[2023-03-21T11:25:13.928+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_operator_v04', 'install_odbc_3', 'scheduled__2023-03-20T00:00:00+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/python_operator.py', '--cfg-path', '/tmp/tmpq2y3246b']
[2023-03-21T11:25:13.937+0000] {standard_task_runner.py:83} INFO - Job 259: Subtask install_odbc_3
[2023-03-21T11:25:14.251+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_python_operator_v04.install_odbc_3 scheduled__2023-03-20T00:00:00+00:00 [running]> on host cfacfd39f993
[2023-03-21T11:25:14.444+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mr.Phi
AIRFLOW_CTX_DAG_ID=dag_with_python_operator_v04
AIRFLOW_CTX_TASK_ID=install_odbc_3
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-20T00:00:00+00:00
[2023-03-21T11:25:14.446+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-21T11:25:14.449+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'apt-get update']
[2023-03-21T11:25:14.470+0000] {subprocess.py:86} INFO - Output:
[2023-03-21T11:25:15.029+0000] {subprocess.py:93} INFO - Reading package lists...
[2023-03-21T11:25:15.041+0000] {subprocess.py:93} INFO - E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
[2023-03-21T11:25:15.042+0000] {subprocess.py:93} INFO - E: Unable to lock directory /var/lib/apt/lists/
[2023-03-21T11:25:15.043+0000] {subprocess.py:97} INFO - Command exited with return code 100
[2023-03-21T11:25:15.056+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 100.
[2023-03-21T11:25:15.062+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_operator_v04, task_id=install_odbc_3, execution_date=20230320T000000, start_date=20230321T112513, end_date=20230321T112515
[2023-03-21T11:25:15.077+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 259 for task install_odbc_3 (Bash command failed. The command returned a non-zero exit code 100.; 7333)
[2023-03-21T11:25:15.099+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-21T11:25:15.119+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
