[2023-03-20T19:30:50.872+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_operator_v03.install_odbc scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-20T19:30:50.883+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_operator_v03.install_odbc scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-20T19:30:50.883+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T19:30:50.884+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-20T19:30:50.885+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-20T19:30:50.902+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): install_odbc> on 2023-03-19 00:00:00+00:00
[2023-03-20T19:30:50.906+0000] {standard_task_runner.py:55} INFO - Started process 5119 to run task
[2023-03-20T19:30:50.909+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_operator_v03', 'install_odbc', 'scheduled__2023-03-19T00:00:00+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/python_operator.py', '--cfg-path', '/tmp/tmph099zv12']
[2023-03-20T19:30:50.911+0000] {standard_task_runner.py:83} INFO - Job 230: Subtask install_odbc
[2023-03-20T19:30:50.977+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_python_operator_v03.install_odbc scheduled__2023-03-19T00:00:00+00:00 [running]> on host 0460afb3b5cd
[2023-03-20T19:30:51.053+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mr.Phi
AIRFLOW_CTX_DAG_ID=dag_with_python_operator_v03
AIRFLOW_CTX_TASK_ID=install_odbc
AIRFLOW_CTX_EXECUTION_DATE=2023-03-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-19T00:00:00+00:00
[2023-03-20T19:30:51.059+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-20T19:30:51.061+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -\n    curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list\n    apt-get update\n    ACCEPT_EULA=Y apt-get install -y msodbcsql17\n    ']
[2023-03-20T19:30:51.069+0000] {subprocess.py:86} INFO - Output:
[2023-03-20T19:30:51.081+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-03-20T19:30:51.082+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-03-20T19:30:51.261+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
[2023-03-20T19:30:51.267+0000] {subprocess.py:93} INFO - E: This command can only be used by root.
[2023-03-20T19:30:51.472+0000] {subprocess.py:93} INFO - 100   983  100   983    0     0   2520      0 --:--:-- --:--:-- --:--:--  2520
[2023-03-20T19:30:51.473+0000] {subprocess.py:93} INFO - (23) Failed writing body
[2023-03-20T19:30:51.475+0000] {subprocess.py:93} INFO - /bin/bash: line 3: /etc/apt/sources.list.d/mssql-release.list: Permission denied
[2023-03-20T19:30:51.495+0000] {subprocess.py:93} INFO - Reading package lists...
[2023-03-20T19:30:51.498+0000] {subprocess.py:93} INFO - E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
[2023-03-20T19:30:51.505+0000] {subprocess.py:93} INFO - E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
[2023-03-20T19:30:51.505+0000] {subprocess.py:93} INFO - E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
[2023-03-20T19:30:51.506+0000] {subprocess.py:97} INFO - Command exited with return code 100
[2023-03-20T19:30:51.520+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 100.
[2023-03-20T19:30:51.527+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_operator_v03, task_id=install_odbc, execution_date=20230319T000000, start_date=20230320T193050, end_date=20230320T193051
[2023-03-20T19:30:51.541+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 230 for task install_odbc (Bash command failed. The command returned a non-zero exit code 100.; 5119)
[2023-03-20T19:30:51.564+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-20T19:30:51.591+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
